# open the file manager
[[session]]
name = "Downloads 📥"
path = "~/Downloads"
startup_command = ""

# open a file
[[session]]
name = "tmux config"
path = "/Users/ane/dotfiles/tmux"
startup_command = "nvim .tmux.conf"

[[session]]
name = "sesh config"
path = "/Users/ane/dotfiles/sesh/.config/sesh"
startup_command = "nvim sesh.toml"

[[session]]
name = "nvim config"
path = "/Users/ane/nvim/.config/nvim"
startup_command = "nvim plugins.lua"

# run a script to startup a node project
[[session]]
path = "~/c/joshmedeski.com"
startup_script = "~/.config/sesh/scripts/node_dev"
